Validate that action is defined
The Actions runner does not verify that inputs marked as 'required' are
actually given: https://github.com/actions/runner/issues/1070

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -60,6 +60,11 @@ runs:
         actionref: ${{ github.action_ref }}
         actionrepo: ${{ github.action_repository }}
       run: |
+        if [ -z "$action" ]; then
+          echo "::error::Action input is required (deploy/remove)" >&2
+          exit 1
+        fi
+
         if [ "$action" != "deploy" ] && [ "$action" != "remove" ]; then
           echo "::error::Unknown action $action" >&2
           exit 1
